class JsonSerializer:
    def __init__(self, options: dict = None) -> None: ...
    def serialize(self, obj: object) -> str: ...
    def deserialize(self, json_str: str, cls: type) -> object: ...
    def serealize_to_file(self, obj: object, file_path: str): ...
    def deserialize_from_file(self, file_path: str, cls: type) -> object: ...
    def register_custom_type(self, cls: type, serializer: callable): ...
    def handle_error(self, error: Exception): ...
    def is_serializable(self, obj: object) -> dict: ...
    def get_serialization_options(self) -> dict: ...