# (c) KiryxaTech, 2024. Apache License 2.0. See the LICENSE file.

from abc import ABC, abstractmethod
from typing import Any, Dict, Union


class Entity(ABC):
    """
    Abstract base class for creating JSON entities in the OOJ library.

    This `Entity` class serves as a foundation for defining JSON-like structures,
    establishing a standard for string representation and equality operations. 
    Each subclass is required to implement the `to_dict` method, which provides a 
    dictionary representation of the object. This makes it easy to convert 
    instances into JSON-compatible formats.

    Methods:
        __str__() -> str:
            Returns a string representation of the object, leveraging the 
            dictionary representation provided by `to_dict`.

        __eq__(value: Union[Dict[str, Any], 'Entity']) -> bool:
            Compares the current object to another `Entity` or dictionary.
            Two objects are considered equal if their string representations match.

        __ne__(value: Union[Dict[str, Any], 'Entity']) -> bool:
            Compares the current object to another `Entity` or dictionary.
            Two objects are considered not equal if their string representations differ.

        to_dict() -> Dict[str, Any]:
            Abstract method. Should be implemented in each subclass to define 
            the dictionary representation of the object, which will be used 
            for string representation and comparisons.
    """

    def __str__(self):
        """
        Returns a string representation of the object based on its dictionary form.

        This method converts the dictionary representation provided by `to_dict` 
        into a string format, making it suitable for printing and logging.

        Returns:
            str: A string that represents the dictionary form of the object.
        """
        return str(self.to_dict())
    
    def __eq__(self, value: Union[Dict[str, Any], 'Entity']) -> bool:
        """
        Compares the current object with another `Entity` instance or dictionary.

        Two objects are considered equal if their string representations, as
        generated by the `__str__` method, are the same.

        Args:
            value (Union[Dict[str, Any], 'Entity']): The object to compare against.

        Returns:
            bool: `True` if the objects are equal, `False` otherwise.
        """
        return str(self) == str(value)
        
    def __ne__(self, value: Union[Dict[str, Any], 'Entity']) -> bool:
        """
        Compares the current object with another `Entity` instance or dictionary.

        Two objects are considered not equal if their string representations, 
        as generated by the `__str__` method, differ.

        Args:
            value (Union[Dict[str, Any], 'Entity']): The object to compare against.

        Returns:
            bool: `True` if the objects are not equal, `False` otherwise.
        """
        return str(self) != str(value)
    
    @abstractmethod
    def to_dict(self) -> Dict[str, Any]:
        """
        Abstract method that must be implemented in each subclass to return 
        a dictionary representation of the object.

        This dictionary representation serves as the basis for the `__str__`, 
        `__eq__`, and `__ne__` methods, providing a JSON-compatible view of 
        the object's data.

        Returns:
            Dict[str, Any]: A dictionary representing the object's data.
        """
        pass